/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.DbConnection;
import Model.tb_login;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FormUtama extends javax.swing.JFrame {

    DbConnection con;
    Statement st;
    ResultSet rs;
    
    public FormUtama() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - getWidth()) / 2;
        int y = (dim.height - getHeight()) / 2;
        setLocation(x, y);
        CheckRole();
        CheckPrevileges();
    }

    private void CheckRole(){
        con = new DbConnection();
        try{
            st = con.connect().createStatement();
            rs = st.executeQuery("SELECT *FROM tb_login WHERE username = '"+tb_login.getUsername()+"'");
            if(rs.next()){
                tb_login.setRole(rs.getString("role"));
            }
        }catch(SQLException e){
            
        }
    }
    
    private void CheckPrevileges(){
        String role = tb_login.getRole();
        
        if(role.equals("SUPERADMIN")){
            menuDataKaryawab.setEnabled(false);
            menuProses.setEnabled(false);
        }
        else{
            menuPengguna.setEnabled(false);
        }
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        background_With_Title1 = new Controller.Background_With_Title();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuPengguna = new javax.swing.JMenuItem();
        menuDataKaryawab = new javax.swing.JMenuItem();
        menuProses = new javax.swing.JMenu();
        menuPenggajian = new javax.swing.JMenuItem();
        menuCek = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background_With_Title1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout background_With_Title1Layout = new javax.swing.GroupLayout(background_With_Title1);
        background_With_Title1.setLayout(background_With_Title1Layout);
        background_With_Title1Layout.setHorizontalGroup(
            background_With_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1365, Short.MAX_VALUE)
        );
        background_With_Title1Layout.setVerticalGroup(
            background_With_Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        jMenu3.setText("INPUT");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuPengguna.setText("TAMBAH PENGGUNA");
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        jMenu3.add(menuPengguna);

        menuDataKaryawab.setText("TAMBAH DATA KARYAWAN");
        menuDataKaryawab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataKaryawabActionPerformed(evt);
            }
        });
        jMenu3.add(menuDataKaryawab);

        jMenuBar2.add(jMenu3);

        menuProses.setText("PROCESS");
        menuProses.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuPenggajian.setText("PENGGAJIAN");
        menuPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggajianActionPerformed(evt);
            }
        });
        menuProses.add(menuPenggajian);

        menuCek.setText("CEK & UBAH DATA KARYAWAN");
        menuCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCekActionPerformed(evt);
            }
        });
        menuProses.add(menuCek);

        jMenuBar2.add(menuProses);

        jMenu5.setText("REPORT");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem4.setText("LAPORAN DATA KARYAWAN");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem7.setText("LAPORAN PENGGAJIAN");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar2.add(jMenu5);

        jMenu7.setText("SETTING");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem5.setText("GANTI PASSWORD");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        jMenuBar2.add(jMenu7);

        jMenu6.setText("LOG OUT");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_With_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_With_Title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        // TODO add your handling code here:
        new FormPengguna().show();
    }//GEN-LAST:event_menuPenggunaActionPerformed

    private void menuDataKaryawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataKaryawabActionPerformed
        // TODO add your handling code here:
        new FormDataMaster().show();
    }//GEN-LAST:event_menuDataKaryawabActionPerformed

    private void menuCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCekActionPerformed
        // TODO add your handling code here:
        new FormTampilDataKaryawan().show();
    }//GEN-LAST:event_menuCekActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FormCetakDataKaryawan().show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if(ok == 0){
            JOptionPane.showMessageDialog(null, "Goodbye "+ tb_login.getUsername());
            System.exit(ok);
        }
        else{
            
        }
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new FormSetting().show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggajianActionPerformed
        // TODO add your handling code here:
        new FormPenggajian().show();
    }//GEN-LAST:event_menuPenggajianActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new FormCetakPenggajian().show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controller.Background_With_Title background_With_Title1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem menuCek;
    private javax.swing.JMenuItem menuDataKaryawab;
    private javax.swing.JMenuItem menuPenggajian;
    private javax.swing.JMenuItem menuPengguna;
    private javax.swing.JMenu menuProses;
    // End of variables declaration//GEN-END:variables
}
